# Generated by Django 5.0 on 2024-01-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
